name: A workflow for my Prime JS file
on: push
jobs:
  build:
    name: unit-test for prime
    runs-on: ubuntu-latest
    steps:
       uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
